[package]
name = "tauri-plugin-keyring"
version = "0.1.0"
authors = [ "Huakun Shen" ]
description = ""
license = "MIT"
edition = "2021"
rust-version = "1.77.2"
exclude = ["/examples", "/webview-dist", "/webview-src", "/node_modules"]
links = "tauri-plugin-keyring"

[dependencies]
tauri = { version = "2.1.0" }
serde = "1.0"
thiserror = "2"
keyring = { version = "3.6.1", features = ["apple-native", "windows-native", "sync-secret-service"] }

[build-dependencies]
tauri-plugin = { version = "2.0.3", features = ["build"] }
